import type { CrowdLevel } from '@/types/place'
import type { RoutePlan } from '@/lib/route-timing'
import { createDebouncedSync, pullFromServer } from '@/lib/db-sync'
import { haversineKm } from '@/lib/haversine'

// Same storage key as the hslee reference (`lib/routes.ts`) so Step 10's
// RoutePage can read this draft directly once it's built.
const STORAGE_KEY = 'k-vibe-current-route'

// See DB_INTEGRATION_REQUEST.md — unlike route-progress/persona-preference,
// edits here can happen continuously (drag reorder), so pushes are debounced
// to one full-draft PUT after things settle. `flushRouteDraftSync()` is
// wired up at the app shell (app-layout.tsx) to catch in-flight edits on tab
// hide/page leave so a debounce window in progress isn't silently dropped.
const routeDraftSync = createDebouncedSync('/route-draft')
export const flushRouteDraftSync = routeDraftSync.flush
// Persists the Persona-generated RoutePlan so RoutePage can show the docent
// player only for routes that originated from the Persona feature.
const PERSONA_PLAN_KEY = 'k-vibe-persona-plan'

export interface RouteStop {
  id: string
  // TourAPI contentid — the actual place's identity, distinct from `id`
  // (a stop *instance* identifier). Needed wherever `id` gets a suffix
  // (e.g. PersonaPage's `${s.id}-${ts}` for repeat adds) so the backend can
  // still FK the stop to the right `location` row. See FRONTEND_TODO_placeId.md.
  placeId?: string
  name: string
  category: string
  address: string
  lat: number
  lng: number
  crowdLevel?: CrowdLevel
  description?: string
  tags?: string[]
  stayMinutes?: number
  startTime?: string
  // ISO "YYYY-MM-DD" — only meaningful when isAnchor is true. Non-anchor stops
  // get their date/startTime computed at render time by lib/route-schedule.ts.
  date?: string
  isAnchor?: boolean
  // true when this stop was generated by the Persona feature — used to show
  // the Docent button only on Persona-originated stops.
  fromPersona?: boolean
  // Real place photo (location.image_url) carried over from the Persona
  // result screen's RouteStop, so "내 루트" can keep showing it after the
  // stop is added.
  imageUrl?: string
}

// Backend's PUT /route-draft/{username} takes {stops, plan} together (see
// backend/presentation_api/routeDraft.py) — plan is stored in a separate
// table (route_draft_meta) but sent in the same request as stops.
function scheduleDraftSync(stops: RouteStop[]): void {
  routeDraftSync.schedule({ stops, plan: readPersonaRoutePlan() })
}

export function readRouteDraft(): RouteStop[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    return raw ? (JSON.parse(raw) as RouteStop[]) : []
  } catch {
    return []
  }
}

// 지도/페르소나/SNS분석/찜한장소 4개 진입점이 서로 다른 id 체계를 쓴다(지도:
// TourAPI contentId 또는 `kakao-{id}` / 페르소나: `{personaId}-{장소명}` /
// SNS분석: `analysisStopId()` / 찜한장소: 지도와 동일 `place.id` 재사용) —
// 같은 실제 장소라도 진입점이 다르면 placeId/id만으로는 원천적으로 같은
// 장소인지 못 잡는다. 이름(정규화 후 비교)과 좌표(하버사인 거리)가 둘 다
// 가까우면 같은 장소로 간주하는 보조 판정을 추가.
const SAME_PLACE_DISTANCE_KM = 0.05 // 50m — 같은 건물/부지 오차 범위

function normalizePlaceName(name: string): string {
  return name.trim().toLowerCase().replace(/\s+/g, '')
}

// 2026-09 QA 10번 — 같은 장소를 중복 추가할 수 있던 버그. `id`는 스팟
// *인스턴스* 식별자라 PersonaPage가 매번 `${s.id}-${ts}`로 새 id를 만들어서
// (같은 페르소나 루트를 두 번 "추가"하면) 기존 `id` 기준 upsert로는 못
// 잡았음 — 실제 장소 정체성인 `placeId`(없으면 `id`) 기준으로 같은 장소인지
// 판단한다. 2026-09 태스크보드 8번 — 그것만으로는 서로 다른 진입점끼리는
// 여전히 못 잡아서(위 주석 참고), id/placeId가 다르더라도 이름+좌표가
// 가까우면 같은 장소로 판정하는 보조 조건을 추가.
function isSamePlace(a: RouteStop, b: RouteStop): boolean {
  if ((a.placeId ?? a.id) === (b.placeId ?? b.id)) return true
  if (!Number.isFinite(a.lat) || !Number.isFinite(a.lng) || !Number.isFinite(b.lat) || !Number.isFinite(b.lng)) {
    return false
  }
  if (normalizePlaceName(a.name) !== normalizePlaceName(b.name)) return false
  return haversineKm(a.lat, a.lng, b.lat, b.lng) <= SAME_PLACE_DISTANCE_KM
}

// AnalyzePage에서 만드는 stop id 규칙을 여기 한 곳에 둔다 — AnalyzePage(추가할
// 때)와 AnalysisResultList(이미 추가됐는지 표시할 때) 둘 다 같은 id를 만들어야
// 같은 장소로 인식되는데, 템플릿 문자열을 두 군데 따로 적어두면 나중에 한쪽만
// 바뀌었을 때 "추가됨" 표시가 조용히 깨질 수 있어서 함수로 공유한다.
export function analysisStopId(videoId: string, placeName: string): string {
  return `analysis-${videoId}-${placeName}`
}

// AnalysisResultList가 카드마다 "이미 루트에 추가됨"을 보여주는 데 쓴다 — 매번
// readRouteDraft() 전체를 훑는 대신, 호출부(AnalyzePage)가 한 번 계산해서
// Set으로 넘겨주는 걸 가정한 얕은 헬퍼.
export function readRouteDraftStopIds(): Set<string> {
  return new Set(readRouteDraft().map((s) => s.placeId ?? s.id))
}

export interface AddStopOutcome {
  stops: RouteStop[]
  // false면 같은 장소가 이미 루트에 있어서 새로 추가되지 않았음 — 호출부가
  // "루트에 추가됐어요" 대신 "이미 추가된 루트예요"를 보여줄 때 사용.
  added: boolean
}

export function addStopToRouteDraft(stop: RouteStop): AddStopOutcome {
  const existing = readRouteDraft()
  const added = !existing.some((s) => isSamePlace(s, stop))
  const next = [...existing.filter((s) => !isSamePlace(s, stop)), stop]
  localStorage.setItem(STORAGE_KEY, JSON.stringify(next))
  scheduleDraftSync(next)
  return { stops: next, added }
}

export interface AddStopsOutcome {
  stops: RouteStop[]
  addedCount: number
  skippedCount: number
}

/**
 * Upserts multiple stops at once — used when a feature (e.g. Analyze, Persona)
 * generates several stops together. Merges into whatever's already in the
 * draft (e.g. from Map) rather than replacing it, so stops added from
 * different entry points can be combined into one route.
 */
export function addStopsToRouteDraft(stops: RouteStop[]): AddStopsOutcome {
  const existing = readRouteDraft()
  const addedCount = stops.filter((s) => !existing.some((e) => isSamePlace(e, s))).length
  const next = [...existing.filter((s) => !stops.some((incoming) => isSamePlace(incoming, s))), ...stops]
  localStorage.setItem(STORAGE_KEY, JSON.stringify(next))
  scheduleDraftSync(next)
  return { stops: next, addedCount, skippedCount: stops.length - addedCount }
}

/**
 * Replaces the whole draft with RoutePage's own edited order/schedule.
 * Unlike addStop(s)ToRouteDraft (which merge in stops from another feature),
 * this is the route editor saving the same stops it's already showing —
 * not a cross-feature merge, so a full overwrite is safe here.
 */
export function saveRouteDraft(stops: RouteStop[]): RouteStop[] {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(stops))
  scheduleDraftSync(stops)
  return stops
}

export function savePersonaRoutePlan(plan: RoutePlan): void {
  localStorage.setItem(PERSONA_PLAN_KEY, JSON.stringify(plan))
  scheduleDraftSync(readRouteDraft())
}

export function readPersonaRoutePlan(): RoutePlan | null {
  try {
    const raw = localStorage.getItem(PERSONA_PLAN_KEY)
    return raw ? (JSON.parse(raw) as RoutePlan) : null
  } catch {
    return null
  }
}

export function clearPersonaRoutePlan(): void {
  localStorage.removeItem(PERSONA_PLAN_KEY)
  scheduleDraftSync(readRouteDraft())
}

// 로그인 시 서버(GET /route-draft/{username})에 저장된 루트를 로컬로 복원.
// 로그인 전 게스트 상태에서 이미 로컬에 담아둔 스팟은 지우지 않고 합치되,
// 순서는 "계정(서버) 루트가 먼저, 로그아웃 상태에서 새로 추가한 로컬 스팟이
// 그 아래"가 되어야 함 — addStopsToRouteDraft는 반대 순서(기존이 먼저,
// 새로 들어오는 게 뒤)라 여기서는 재사용하지 않고 서버 목록을 앞에 두고
// 로컬에만 있는 스팟을 뒤에 이어붙인다.
export async function restoreRouteDraftFromServer(): Promise<void> {
  const data = await pullFromServer<{ stops: RouteStop[]; plan: RoutePlan | null }>('/route-draft')
  if (!data) return
  if (data.stops?.length) {
    const localOnly = readRouteDraft().filter((local) => !data.stops.some((server) => isSamePlace(server, local)))
    const merged = [...data.stops, ...localOnly]
    localStorage.setItem(STORAGE_KEY, JSON.stringify(merged))
    scheduleDraftSync(merged)
  }
  if (data.plan && !readPersonaRoutePlan()) savePersonaRoutePlan(data.plan)
}
