import type { CrowdLevel } from '@/types/place'
import type { RoutePlan } from '@/lib/route-timing'
import { createDebouncedSync, pullFromServer } from '@/lib/db-sync'

// Same storage key as the hslee reference (`lib/routes.ts`) so Step 10's
// RoutePage can read this draft directly once it's built.
const STORAGE_KEY = 'k-vibe-current-route'

// See DB_INTEGRATION_REQUEST.md — unlike route-progress/persona-preference,
// edits here can happen continuously (drag reorder), so pushes are debounced
// to one full-draft PUT after things settle. `flushRouteDraftSync()` is
// wired up at the app shell (app-layout.tsx) to catch in-flight edits on tab
// hide/page leave so a debounce window in progress isn't silently dropped.
const routeDraftSync = createDebouncedSync('/route-draft')
export const flushRouteDraftSync = routeDraftSync.flush
// Persists the Persona-generated RoutePlan so RoutePage can show the docent
// player only for routes that originated from the Persona feature.
const PERSONA_PLAN_KEY = 'k-vibe-persona-plan'

export interface RouteStop {
  id: string
  // TourAPI contentid — the actual place's identity, distinct from `id`
  // (a stop *instance* identifier). Needed wherever `id` gets a suffix
  // (e.g. PersonaPage's `${s.id}-${ts}` for repeat adds) so the backend can
  // still FK the stop to the right `location` row. See FRONTEND_TODO_placeId.md.
  placeId?: string
  name: string
  category: string
  address: string
  lat: number
  lng: number
  crowdLevel?: CrowdLevel
  description?: string
  tags?: string[]
  stayMinutes?: number
  startTime?: string
  // ISO "YYYY-MM-DD" — only meaningful when isAnchor is true. Non-anchor stops
  // get their date/startTime computed at render time by lib/route-schedule.ts.
  date?: string
  isAnchor?: boolean
  // true when this stop was generated by the Persona feature — used to show
  // the Docent button only on Persona-originated stops.
  fromPersona?: boolean
}

// Backend's PUT /route-draft/{username} takes {stops, plan} together (see
// backend/presentation_api/routeDraft.py) — plan is stored in a separate
// table (route_draft_meta) but sent in the same request as stops.
function scheduleDraftSync(stops: RouteStop[]): void {
  routeDraftSync.schedule({ stops, plan: readPersonaRoutePlan() })
}

export function readRouteDraft(): RouteStop[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    return raw ? (JSON.parse(raw) as RouteStop[]) : []
  } catch {
    return []
  }
}

// 2026-09 QA 10번 — 같은 장소를 중복 추가할 수 있던 버그. `id`는 스팟
// *인스턴스* 식별자라 PersonaPage가 매번 `${s.id}-${ts}`로 새 id를 만들어서
// (같은 페르소나 루트를 두 번 "추가"하면) 기존 `id` 기준 upsert로는 못
// 잡았음 — 실제 장소 정체성인 `placeId`(없으면 `id`) 기준으로 같은 장소인지
// 판단한다.
function isSamePlace(a: RouteStop, b: RouteStop): boolean {
  return (a.placeId ?? a.id) === (b.placeId ?? b.id)
}

export interface AddStopOutcome {
  stops: RouteStop[]
  // false면 같은 장소가 이미 루트에 있어서 새로 추가되지 않았음 — 호출부가
  // "루트에 추가됐어요" 대신 "이미 추가된 루트예요"를 보여줄 때 사용.
  added: boolean
}

export function addStopToRouteDraft(stop: RouteStop): AddStopOutcome {
  const existing = readRouteDraft()
  const added = !existing.some((s) => isSamePlace(s, stop))
  const next = [...existing.filter((s) => !isSamePlace(s, stop)), stop]
  localStorage.setItem(STORAGE_KEY, JSON.stringify(next))
  scheduleDraftSync(next)
  return { stops: next, added }
}

export interface AddStopsOutcome {
  stops: RouteStop[]
  addedCount: number
  skippedCount: number
}

/**
 * Upserts multiple stops at once — used when a feature (e.g. Analyze, Persona)
 * generates several stops together. Merges into whatever's already in the
 * draft (e.g. from Map) rather than replacing it, so stops added from
 * different entry points can be combined into one route.
 */
export function addStopsToRouteDraft(stops: RouteStop[]): AddStopsOutcome {
  const existing = readRouteDraft()
  const addedCount = stops.filter((s) => !existing.some((e) => isSamePlace(e, s))).length
  const next = [...existing.filter((s) => !stops.some((incoming) => isSamePlace(incoming, s))), ...stops]
  localStorage.setItem(STORAGE_KEY, JSON.stringify(next))
  scheduleDraftSync(next)
  return { stops: next, addedCount, skippedCount: stops.length - addedCount }
}

/**
 * Replaces the whole draft with RoutePage's own edited order/schedule.
 * Unlike addStop(s)ToRouteDraft (which merge in stops from another feature),
 * this is the route editor saving the same stops it's already showing —
 * not a cross-feature merge, so a full overwrite is safe here.
 */
export function saveRouteDraft(stops: RouteStop[]): RouteStop[] {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(stops))
  scheduleDraftSync(stops)
  return stops
}

export function savePersonaRoutePlan(plan: RoutePlan): void {
  localStorage.setItem(PERSONA_PLAN_KEY, JSON.stringify(plan))
  scheduleDraftSync(readRouteDraft())
}

export function readPersonaRoutePlan(): RoutePlan | null {
  try {
    const raw = localStorage.getItem(PERSONA_PLAN_KEY)
    return raw ? (JSON.parse(raw) as RoutePlan) : null
  } catch {
    return null
  }
}

export function clearPersonaRoutePlan(): void {
  localStorage.removeItem(PERSONA_PLAN_KEY)
  scheduleDraftSync(readRouteDraft())
}

// 로그인 시 서버(GET /route-draft/{username})에 저장된 루트를 로컬로 복원.
// 로그인 전 게스트 상태에서 이미 로컬에 담아둔 스팟은 비우거나 덮어쓰지
// 않고, addStopsToRouteDraft의 기존 병합(placeId 중복 제거) 로직으로 합친다
// — 로그인 직전에 만든 로컬 편집을 잃지 않기 위함.
export async function restoreRouteDraftFromServer(): Promise<void> {
  const data = await pullFromServer<{ stops: RouteStop[]; plan: RoutePlan | null }>('/route-draft')
  if (!data) return
  if (data.stops?.length) addStopsToRouteDraft(data.stops)
  if (data.plan && !readPersonaRoutePlan()) savePersonaRoutePlan(data.plan)
}
