import type { CrowdLevel } from '@/types/place'
import type { RoutePlan } from '@/lib/route-timing'
import { createDebouncedSync } from '@/lib/db-sync'

// Same storage key as the hslee reference (`lib/routes.ts`) so Step 10's
// RoutePage can read this draft directly once it's built.
const STORAGE_KEY = 'k-vibe-current-route'

// See DB_INTEGRATION_REQUEST.md — unlike route-progress/persona-preference,
// edits here can happen continuously (drag reorder), so pushes are debounced
// to one full-draft PUT after things settle. `flushRouteDraftSync()` is
// wired up at the app shell (app-layout.tsx) to catch in-flight edits on tab
// hide/page leave so a debounce window in progress isn't silently dropped.
const routeDraftSync = createDebouncedSync('/route-draft')
export const flushRouteDraftSync = routeDraftSync.flush
// Persists the Persona-generated RoutePlan so RoutePage can show the docent
// player only for routes that originated from the Persona feature.
const PERSONA_PLAN_KEY = 'k-vibe-persona-plan'

export interface RouteStop {
  id: string
  // TourAPI contentid — the actual place's identity, distinct from `id`
  // (a stop *instance* identifier). Needed wherever `id` gets a suffix
  // (e.g. PersonaPage's `${s.id}-${ts}` for repeat adds) so the backend can
  // still FK the stop to the right `location` row. See FRONTEND_TODO_placeId.md.
  placeId?: string
  name: string
  category: string
  address: string
  lat: number
  lng: number
  crowdLevel?: CrowdLevel
  description?: string
  tags?: string[]
  stayMinutes?: number
  startTime?: string
  // ISO "YYYY-MM-DD" — only meaningful when isAnchor is true. Non-anchor stops
  // get their date/startTime computed at render time by lib/route-schedule.ts.
  date?: string
  isAnchor?: boolean
  // true when this stop was generated by the Persona feature — used to show
  // the Docent button only on Persona-originated stops.
  fromPersona?: boolean
}

// Backend's PUT /route-draft/{username} takes {stops, plan} together (see
// backend/presentation_api/routeDraft.py) — plan is stored in a separate
// table (route_draft_meta) but sent in the same request as stops.
function scheduleDraftSync(stops: RouteStop[]): void {
  routeDraftSync.schedule({ stops, plan: readPersonaRoutePlan() })
}

export function readRouteDraft(): RouteStop[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    return raw ? (JSON.parse(raw) as RouteStop[]) : []
  } catch {
    return []
  }
}

export function addStopToRouteDraft(stop: RouteStop): RouteStop[] {
  const next = [...readRouteDraft().filter((s) => s.id !== stop.id), stop]
  localStorage.setItem(STORAGE_KEY, JSON.stringify(next))
  scheduleDraftSync(next)
  return next
}

/**
 * Upserts multiple stops at once — used when a feature (e.g. Analyze, Persona)
 * generates several stops together. Merges into whatever's already in the
 * draft (e.g. from Map) rather than replacing it, so stops added from
 * different entry points can be combined into one route.
 */
export function addStopsToRouteDraft(stops: RouteStop[]): RouteStop[] {
  const incomingIds = new Set(stops.map((s) => s.id))
  const next = [...readRouteDraft().filter((s) => !incomingIds.has(s.id)), ...stops]
  localStorage.setItem(STORAGE_KEY, JSON.stringify(next))
  scheduleDraftSync(next)
  return next
}

/**
 * Replaces the whole draft with RoutePage's own edited order/schedule.
 * Unlike addStop(s)ToRouteDraft (which merge in stops from another feature),
 * this is the route editor saving the same stops it's already showing —
 * not a cross-feature merge, so a full overwrite is safe here.
 */
export function saveRouteDraft(stops: RouteStop[]): RouteStop[] {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(stops))
  scheduleDraftSync(stops)
  return stops
}

export function savePersonaRoutePlan(plan: RoutePlan): void {
  localStorage.setItem(PERSONA_PLAN_KEY, JSON.stringify(plan))
  scheduleDraftSync(readRouteDraft())
}

export function readPersonaRoutePlan(): RoutePlan | null {
  try {
    const raw = localStorage.getItem(PERSONA_PLAN_KEY)
    return raw ? (JSON.parse(raw) as RoutePlan) : null
  } catch {
    return null
  }
}

export function clearPersonaRoutePlan(): void {
  localStorage.removeItem(PERSONA_PLAN_KEY)
  scheduleDraftSync(readRouteDraft())
}
